### ISSUE TITLE
64-bit binaries

### ISSUE THREAD

**Issue by dpwhittaker** [prepare/Espresso#29]
Would it be possible to add 64-bit binaries of libespr.dll to the native folder?  Our project needs > 2GB of ram, so it has to be built in 64-bit, but we'd like to interface with V8.  We started with VroomJS, but it's on a pretty old version of v8, so we'd like to use this version if possible, but the instructions for building libespr are a little slim.  I'll grab the node source and see if I can piece it together, but it would make the library more useful if they were included.

**Comment by prepare** [comment]
@dpwhittaker 

Thank you for your interest.

Sorry for late reply, I just see this today.

I will test /build /release the 64 bits soon

---
@enginekit,=> please see this :)

**Comment by enginekit** [comment]
please see=> https://github.com/prepare/Espresso/issues/30

prebuilt libespr binary: https://drive.google.com/open?id=0BwCDhBTbZl6Ja1FoVV82LWlzMWc
