### ISSUE TITLE
Create Automate build script for Espresso

### ISSUE THREAD

**Issue by prepare** [prepare/Espresso#30]
The building steps of this might be easier if we have an automate build script.

see (https://github.com/CompilerKit/Espresso/issues/2), (https://github.com/CompilerKit/Espresso/issues/3)

**Comment by enginekit** [comment]
macOS
---

The latest version of Espresso supports .netcore!,

detail =>https://github.com/CompilerKit/Espresso/issues/7

**EasePatcher:**

![10](https://user-images.githubusercontent.com/9301044/26942422-3248194e-4cac-11e7-8d5b-a8233736cc25.png)


**Tests:**

![26](https://user-images.githubusercontent.com/9301044/26942872-da890496-4cad-11e7-915f-30a24caef5f3.png)

![27](https://user-images.githubusercontent.com/9301044/26942918-021a1ffe-4cae-11e7-8d5d-6ab38a2857be.png)

---

**Comment by enginekit** [comment]
Linux  (Ubuntu16)
---

detail =>https://github.com/CompilerKit/Espresso/issues/6

**Ease Patcher:**

![10](https://user-images.githubusercontent.com/9301044/26941087-5c244710-4ca7-11e7-98b9-7a0f15cb2ecd.png)

---

**Tests:**
 
![20](https://user-images.githubusercontent.com/9301044/26941879-4ac77e9e-4caa-11e7-823a-bdbb6b629842.png) 

![21](https://user-images.githubusercontent.com/9301044/26941920-6edb05e4-4caa-11e7-92b1-ed907b837acd.png)

![23](https://user-images.githubusercontent.com/9301044/26942079-f2f6afcc-4caa-11e7-9c85-470436e072c2.png)

**Comment by enginekit** [comment]
Windows7, x64
---
detail => https://github.com/CompilerKit/Espresso/issues/8

**EasePatcher:**

![07](https://user-images.githubusercontent.com/9301044/26943511-07e0be28-4cb0-11e7-9a87-8452b6934b42.png)


---
**Tests:**


![11](https://user-images.githubusercontent.com/9301044/26943986-96459b9c-4cb1-11e7-9c26-25b7d232f375.png)

 ![12](https://user-images.githubusercontent.com/9301044/26944008-a83905a0-4cb1-11e7-808e-5769517d44bc.png)

![13](https://user-images.githubusercontent.com/9301044/26944012-aab0061c-4cb1-11e7-9a23-7e99094b0dd3.png)

**Comment by prepare** [comment]
@enginekit  :+1: , :100: 
Now Espresso supports  .netcore/.netstandard !
with macOS, Linux and Windows sample
