### ISSUE TITLE
Run MathJax in C# using Espresso

### ISSUE THREAD

**Issue by johnny0914** [prepare/Espresso#47]
Is it possible to run complex JS code like MathJax in C# using Espresso?

**Comment by prepare** [comment]
Hello @johnwebner, sorry for late reply.

Espresso has 2 choices of js-engine
1. wraps only V8-engine => Espresso-VE
2. wraps entire  nodejs (+V8-engine) => Espresso-ND

But it don't interface with the browser directly.

if MathJax need real-webbrowser dom then 
    You need to interface the espresso to the browser by yourself.    

But if MathJax can run with _virtual dom_ (eg. jsdom) then
    I think the Espresso can run it.

**Comment by prepare** [comment]
@johnwebner 

for C# + Math Expression + Latex =>
Do you visit this https://github.com/verybadcat/CSharpMath yet?
